Parking-sys (Back-end)/mc/urls.py
from django.conf.urls import url
from . import views

app_name = 'mc'

urlpatterns = [
    url(r'^$', views.u_index, name='index'),
   # url(r'^register/(?P<uname>[a-z]+)/$', views.uregister, name='register'),
  #  url(r'^login/(?P<uname>[a-z]+)/$', views.ulogin, name='login'),
  #  url(r'^login/(?P<uname>[a-z]+)/(?P<lgvalue>[0-9]+)/(?P<ltvalue>[0-9]+)/$', views.upark, name='park'),
    url(r'^(?P<uname>[a-z]+)/find/$', views.upark, name='find'),
    url(r'^(?P<uname>[a-z]+)/book/$', views.ubook, name='book'),
    url(r'^check/$', views.check, name='check'), 
]

Parking-sys (Back-end)/myapp/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^mc/', include('mc.urls')),
]

Parking-sys (Back-end)/mc/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class RegisterUser(models.Model):
    username = models.CharField(max_length=10, primary_key=True)
    
    def __str__(self):
        return self.username
        
class ShawPark(models.Model):
    parkid   = models.IntegerField(primary_key=True)
    lon     = models.FloatField(default=73.7236456)
    let      = models.FloatField(default=24.5968106)
    tot      = models.IntegerField(default=8)
    avail    = models.IntegerField(default=4)
    city     = models.CharField(max_length=10)
    address  = models.CharField(max_length=100)
  
    
    def __str__(self):
        return self.city
        
class UserBook(models.Model):
    givenplot= models.BooleanField(default=False)
    plotid   = models.IntegerField(primary_key=True)
    userpin  = models.IntegerField(default=0)
    
    def __str__(self):
        return self.plotid

Parking-sys (Back-end)/mc/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import requests
import random
import json
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpRequest
from rest_framework.renderers import JSONRenderer
from .models import RegisterUser, ShawPark, UserBook
from .serializers import UserSerializer, ShawSerializer, BookSerializer

def u_index(request):
    return HttpResponse("<h1>Hello, motherfucker!<h1>", content_type="text/html")

def uregister(request, uname):
    dup_user = RegisterUser.objects.filter(username=uname).exists()
    if dup_user:
       return HttpResponse("<h1>Choose different username.<h1>", content_type="text/html")
    else:
       user = RegisterUser(username=uname)
       user.save()
       return HttpResponse("<h1>you have been successfully registered!<h1>", content_type="text/html")
       
def ulogin(request, uname):
    user = get_object_or_404(RegisterUser, username=uname)
    
    userserializer = UserSerializer(user)
    userjson = JSONRenderer().render(userserializer.data)
    
    return HttpResponse(userjson, content_type="application/json")
        
def upark(request, uname):
    shawpark = ShawPark(parkid=1, city="Udaipur", address="C-31, Surajpole")
    shawpark.save()	
    
    shawserializer = ShawSerializer(shawpark)
    shawjson = JSONRenderer().render(shawserializer.data)
    
    return HttpResponse(shawjson, content_type="application/json")
    
def ubook(request, uname):
    uRl = "http://192.168.43.224:8080/"
    req = requests.get(url=uRl).json()
    plot=[]  
    data = json.loads(req["mystring"])
    for c in data:
        if int(c)<58 and int(c)>47:
            plot.append(int(c))	

    for i in plot:
        usarbook=UserBook(givenplot=False, plotid=i, userpin=random.randint(1,10)*1000)
        usarbook.save()

    usarbok = UserBook.objects.filter(givenplot=False)
    usarbok.givenplot = False
    usarbok.save()
    
    bokserializer = BookSerializer(usarbok)
    bokjson = JSONRenderer().render(bokserializer.data)
    
    return HttpResponse(bokjson, content_type="application/json")
   
def check(request):
    #template = loader.get_template('mc/index.html')
    #return HttpResponse(template.render(request))
    if request.method == 'GET':
       return render(request, 'mc/index.html')
    else:
       peen = request.POST.get('PIN')
       userexists = UserBook.objects.filter(userpin=peen).exists()

    if userexists :
      # return render('mc/index.html')
       return HttpResponse("<h1>Correct pin!<h1>", content_type="text/html")
    else:
       return HttpResponse("<h1>Wrong pin!<h1>", content_type="text/html")

Parking-sys (Back-end)/mc/templates/mc/index.html
<!doctype html>
<html>
<head>
	<title>Parking System</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'mc/style.css' %}"/>	
	<!--link href="css/bootstrap.min.css" rel="stylesheet"-->
</head>
<body>
	<div class="main">
		<b><h1> Smart Parking Reservation </h1></b>
		<h2>Entering Parking </h2>
		<form action="{% url 'mc:check' %}" method="POST">
			{% csrf_token %}
			<!--p> <label for="PIN"> PIN </label-->
			<input style="text-align:center;width:230px;border-radius:5px;" type="text" name="PIN" placeholder="PIN" size="24" required="required" value="{{ request.GET.PIN }}"/> <!--/p-->
			<br><br>
			<input style="width:230px;border-radius:8px;" type="submit" name="Enter" value="Enter" />
		</form>
		<h2>Exiting Parking </h2>
		<form>
			<input style="text-align:center;width:230px;border-radius:5px;" type="text" name="PIN" placeholder="PIN" size="24" required="required" /> <!--/p-->
			<br></br>
			<input style="width:230px;border-radius:8px;" type="submit" name="Exit" value="Exit" />
		</form>
	</div>
		</body>
</html>